#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import sys
import unittest
from assets.stub_android import stub_api_model
from assets.stub_android import stub_android
import open_close_controller

def print_patterns(patterns):
    def wrapper(fn):
        def _(self):
            print
            print "<<TEST>> %s" % (", ".join(patterns))
            fn(self)
        return _
    return wrapper


def run_pending_tasks(fn):
    def _(self):
        fn(self)

        while len(self.pending_tasks) > 0:
            # http://stackoverflow.com/questions/2612802/how-to-clone-or-copy-a-list-in-python
            # Use instead of a weird syntax new_list = old_list[:]
            pending_tasks = list(self.pending_tasks)
            self.pending_tasks[:] = []

            for task in pending_tasks:
                task()  # Maybe added into self.pending_tasks

    return _


class TestOpenCloseController(unittest.TestCase):
    def setUp(self):
        super(TestOpenCloseController, self).setUp()
        self.pending_tasks = []
        self.timer_tasks = []
        self.savedInstanceState = {}
        self.activityA = stub_android.StubActivity()
        self.activityA.delegate_instance = \
            open_close_controller.OpenCloseController(self.activityA,
                                               self.pending_tasks, self.timer_tasks)
        self.activityB = stub_android.StubActivity()
        self.activityB.delegate_instance = \
            open_close_controller.OpenCloseController(self.activityB,
                                               self.pending_tasks, self.timer_tasks)

    def tearDown(self):
        super(TestOpenCloseController, self).tearDown()

    def _run_timer_tasks(self):
        timer_tasks = list(self.timer_tasks)
        self.timer_tasks[:] = []

        for task in timer_tasks:
            task()  # Maybe added into self.timer_tasks

    @run_pending_tasks
    def onCreateA(self):
        self.activityA.onCreate(None)

    @run_pending_tasks
    def onResumeA(self):
        self.activityA.onResume()

    @run_pending_tasks
    def onPauseA(self):
        self.activityA.onPause()

    @run_pending_tasks
    def onSaveInstanceStateA(self):
        self.activityA.onSaveInstanceState(self.savedInstanceState)

    @run_pending_tasks
    def onCreateB(self):
        self.activityB.onCreate(self.savedInstanceState)

    @run_pending_tasks
    def onResumeB(self):
        self.activityB.onResume()

    @run_pending_tasks
    def onPauseB(self):
        self.activityB.onPause()

    @run_pending_tasks
    def closeDialog(self):
        self.activityB.delegate_instance.closeDialog()

    @run_pending_tasks
    def cancelDialog(self):
        self.activityB.delegate_instance.cancelDialog()

    def startToOpen(self):
        self.activityA.delegate_instance.startToOpen()

    def startToClose(self):
        self.activityA.delegate_instance.startToClose()

    def open(self):
        self.activityA.delegate_instance.open(animated=False)

    def close(self):
        self.activityA.delegate_instance.close(animated=False)

    def expectInOpen(self):
        self.assertEqual('OPEN', self.activityB.delegate_instance.state_machine.getCurrentStateName())

    def expectInClosed(self):
        self.assertEqual('CLOSED', self.activityB.delegate_instance.state_machine.getCurrentStateName())

    # %%

    #
    # 以下の行は自動生成されているので直接編集しないでください。
    #
    # Generated by Test Case Generator
    # https://rubygems.org/gems/test_case_generator
    #

    @print_patterns(['onCreateA', 'startToOpen', 'onResumeA', 'close', 'open', 'onPauseA', 'onSaveInstanceStateA', 'onCreateB', 'onResumeB', 'onPauseB', 'expectInOpen'])
    def test_onCreateA_startToOpen_onResumeA_close_open_onPauseA_onSaveInstanceStateA_onCreateB_onResumeB_onPauseB_expectInOpen(self):
        self.onCreateA()
        self.startToOpen()
        self.onResumeA()
        self.close()
        self.open()
        self.onPauseA()
        self.onSaveInstanceStateA()
        self.onCreateB()
        self.onResumeB()
        self.onPauseB()
        self.expectInOpen()

    @classmethod
    def checkSanity(cls):
        sane = True
        msg = []
        for method in ['onCreateA', 'startToOpen', 'onResumeA', 'close', 'open', 'onPauseA', 'onSaveInstanceStateA', 'onCreateB', 'onResumeB', 'onPauseB', 'expectInOpen']:
            if not hasattr(cls, method):
                msg += [
                    '    def %s(self):' % method,
                    '        pass',
                    '',
                ]
                sane = False

        if not sane:
            print cls.__name__ + ' must implement following method(s):'
            print
            print "\n".join(msg)
            raise SystemExit(1)


if __name__ == '__main__':
    TestOpenCloseController.checkSanity()
    unittest.main()
