#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import sys
import unittest
import splash_screen_controller
from assets.stub_android import stub_api_model
from assets.stub_android import stub_android


def print_patterns(patterns):
    def wrapper(fn):
        def _(self):
            print
            print "<<TEST>> %s" % (", ".join(patterns))
            fn(self)
        return _
    return wrapper


def run_pending_tasks(fn):
    def _(self):
        fn(self)

        while len(self.pending_tasks) > 0:
            pending_tasks = list(self.pending_tasks)

            self.pending_tasks[:] = []
            for task in pending_tasks:
                task()  # Maybe added into self.pending_tasks

    return _


class TestSplashScreenController(unittest.TestCase):
    def setUp(self):
        super(TestSplashScreenController, self).setUp()
        self.pending_tasks = []
        self.timer_tasks = []
        self.savedInstanceState = {}
        self.model = api_model.ApiModel(api_call_limit=2)
        self.activityA = stub_android.StubActivity()
        self.activityA.delegate_instance = \
            splash_screen_controller.SplashScreenController(self.activityA, self.model,
                                               self.pending_tasks, self.timer_tasks)
        self.activityB = stub_android.StubActivity()
        self.activityB.delegate_instance = \
            splash_screen_controller.SplashScreenController(self.activityB, self.model,
                                               self.pending_tasks, self.timer_tasks)

    def tearDown(self):
        super(TestSplashScreenController, self).tearDown()

    def _run_timer_tasks(self):
        timer_tasks = list(self.timer_tasks)

        self.timer_tasks[:] = []
        for task in timer_tasks:
            task()  # Maybe added into self.timer_tasks

    @run_pending_tasks
    def onCreateA(self):
        self.activityA.onCreate(None)

    @run_pending_tasks
    def onResumeA(self):
        self.activityA.onResume()

    @run_pending_tasks
    def onPauseA(self):
        self.activityA.onPause()

    @run_pending_tasks
    def onSaveInstanceStateA(self):
        self.activityA.onSaveInstanceState(self.savedInstanceState)

    @run_pending_tasks
    def onCreateB(self):
        self.activityB.onCreate(self.savedInstanceState)

    @run_pending_tasks
    def onResumeB(self):
        self.activityB.onResume()

    @run_pending_tasks
    def receiveResponse(self):
        self.model.dispatchEvent()

    @run_pending_tasks
    def onPauseB(self):
        self.activityB.onPause()

    @run_pending_tasks
    def notifyTimedOut(self):
        self._run_timer_tasks()

    def expectInDoorState(self):
        self.assertEqual('READY', self.activityB.delegate_instance.state_machine.getCurrentStateName())

    def expectInErrorDialog(self):
        self.assertEqual('ERROR_DIALOG', self.activityB.delegate_instance.state_machine.getCurrentStateName())

    # %%

    #
    # 以下の行は自動生成されているので直接編集しないでください。
    #
    # Generated by Test Case Generator
    # https://rubygems.org/gems/test_case_generator
    #

    @print_patterns(['onCreateA', 'onResumeA', 'onPauseA', 'onSaveInstanceStateA', 'onCreateB', 'onResumeB', 'receiveResponse', 'onPauseB', 'expectInDoorState'])
    def test_onCreateA_onResumeA_onPauseA_onSaveInstanceStateA_onCreateB_onResumeB_receiveResponse_onPauseB_expectInDoorState(self):
        self.onCreateA()
        self.onResumeA()
        self.onPauseA()
        self.onSaveInstanceStateA()
        self.onCreateB()
        self.onResumeB()
        self.receiveResponse()
        self.onPauseB()
        self.expectInDoorState()

    @print_patterns(['onCreateA', 'onResumeA', 'onPauseA', 'onSaveInstanceStateA', 'onCreateB', 'receiveResponse', 'onResumeB', 'onPauseB', 'expectInDoorState'])
    def test_onCreateA_onResumeA_onPauseA_onSaveInstanceStateA_onCreateB_receiveResponse_onResumeB_onPauseB_expectInDoorState(self):
        self.onCreateA()
        self.onResumeA()
        self.onPauseA()
        self.onSaveInstanceStateA()
        self.onCreateB()
        self.receiveResponse()
        self.onResumeB()
        self.onPauseB()
        self.expectInDoorState()

    @print_patterns(['onCreateA', 'onResumeA', 'onPauseA', 'onSaveInstanceStateA', 'receiveResponse', 'onCreateB', 'onResumeB', 'onPauseB', 'expectInDoorState'])
    def test_onCreateA_onResumeA_onPauseA_onSaveInstanceStateA_receiveResponse_onCreateB_onResumeB_onPauseB_expectInDoorState(self):
        self.onCreateA()
        self.onResumeA()
        self.onPauseA()
        self.onSaveInstanceStateA()
        self.receiveResponse()
        self.onCreateB()
        self.onResumeB()
        self.onPauseB()
        self.expectInDoorState()

    @print_patterns(['onCreateA', 'onResumeA', 'onPauseA', 'receiveResponse', 'onSaveInstanceStateA', 'onCreateB', 'onResumeB', 'onPauseB', 'expectInDoorState'])
    def test_onCreateA_onResumeA_onPauseA_receiveResponse_onSaveInstanceStateA_onCreateB_onResumeB_onPauseB_expectInDoorState(self):
        self.onCreateA()
        self.onResumeA()
        self.onPauseA()
        self.receiveResponse()
        self.onSaveInstanceStateA()
        self.onCreateB()
        self.onResumeB()
        self.onPauseB()
        self.expectInDoorState()

    @print_patterns(['onCreateA', 'onResumeA', 'receiveResponse', 'onPauseA', 'onSaveInstanceStateA', 'onCreateB', 'onResumeB', 'onPauseB', 'expectInDoorState'])
    def test_onCreateA_onResumeA_receiveResponse_onPauseA_onSaveInstanceStateA_onCreateB_onResumeB_onPauseB_expectInDoorState(self):
        self.onCreateA()
        self.onResumeA()
        self.receiveResponse()
        self.onPauseA()
        self.onSaveInstanceStateA()
        self.onCreateB()
        self.onResumeB()
        self.onPauseB()
        self.expectInDoorState()

    @print_patterns(['onCreateA', 'receiveResponse', 'onResumeA', 'onPauseA', 'onSaveInstanceStateA', 'onCreateB', 'onResumeB', 'onPauseB', 'expectInDoorState'])
    def test_onCreateA_receiveResponse_onResumeA_onPauseA_onSaveInstanceStateA_onCreateB_onResumeB_onPauseB_expectInDoorState(self):
        self.onCreateA()
        self.receiveResponse()
        self.onResumeA()
        self.onPauseA()
        self.onSaveInstanceStateA()
        self.onCreateB()
        self.onResumeB()
        self.onPauseB()
        self.expectInDoorState()

    @print_patterns(['onCreateA', 'onResumeA', 'onPauseA', 'onResumeA', 'onPauseA', 'onResumeA', 'notifyTimedOut', 'onPauseA', 'onSaveInstanceStateA', 'onCreateB', 'onResumeB', 'expectInErrorDialog', 'receiveResponse', 'expectInDoorState', 'onPauseB'])
    def test_onCreateA_onResumeA_onPauseA_onResumeA_onPauseA_onResumeA_notifyTimedOut_onPauseA_onSaveInstanceStateA_onCreateB_onResumeB_expectInErrorDialog_receiveResponse_expectInDoorState_onPauseB(self):
        self.onCreateA()
        self.onResumeA()
        self.onPauseA()
        self.onResumeA()
        self.onPauseA()
        self.onResumeA()
        self.notifyTimedOut()
        self.onPauseA()
        self.onSaveInstanceStateA()
        self.onCreateB()
        self.onResumeB()
        self.expectInErrorDialog()
        self.receiveResponse()
        self.expectInDoorState()
        self.onPauseB()

    @classmethod
    def checkSanity(cls):
        sane = True
        msg = []
        for method in ['onCreateA', 'onResumeA', 'onPauseA', 'onSaveInstanceStateA', 'onCreateB', 'onResumeB', 'receiveResponse', 'onPauseB', 'expectInDoorState', 'notifyTimedOut', 'expectInErrorDialog']:
            if not hasattr(cls, method):
                msg += [
                    '    def %s(self):' % method,
                    '        pass',
                    '',
                ]
                sane = False

        if not sane:
            print cls.__name__ + ' must implement following method(s):'
            print
            print "\n".join(msg)
            raise SystemExit(1)


if __name__ == '__main__':
    TestSplashScreenController.checkSanity()
    unittest.main()
