#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import sys
import unittest
import stub_android
import no_network_splash_screen_controller

def print_patterns(patterns):
    def wrapper(fn):
        def _(self):
            print
            print "TEST: %s" % (",".join(patterns))
            fn(self)
        return _
    return wrapper


def run_pending_tasks(fn):
    def _(self):
        fn(self)

        while len(self.pending_tasks) > 0:
            pending_tasks = list(self.pending_tasks)

            self.pending_tasks[:] = []
            for task in pending_tasks:
                task()  # Maybe added into self.pending_tasks

    return _


class TestNoNetworkSplashScreenController(unittest.TestCase):
    def setUp(self):
        super(TestNoNetworkSplashScreenController, self).setUp()
        self.pending_tasks = []
        self.timer_tasks = []
        self.savedInstanceState = {}
        self.activityA = stub_android.StubActivity()
        self.activityA.delegate_instance = \
            no_network_splash_screen_controller.NoNetworkSplashScreenController(self.activityA,
                                               self.pending_tasks, self.timer_tasks)
        self.activityB = stub_android.StubActivity()
        self.activityB.delegate_instance = \
            no_network_splash_screen_controller.NoNetworkSplashScreenController(self.activityB,
                                               self.pending_tasks, self.timer_tasks)

    def tearDown(self):
        super(TestNoNetworkSplashScreenController, self).tearDown()

    def _run_timer_tasks(self):
        timer_tasks = list(self.timer_tasks)

        self.timer_tasks[:] = []
        for task in timer_tasks:
            task()  # Maybe added into self.timer_tasks

    @run_pending_tasks
    def onCreateA(self):
        self.activityA.onCreate(None)

    @run_pending_tasks
    def onResumeA(self):
        self.activityA.onResume()

    @run_pending_tasks
    def onPauseA(self):
        self.activityA.onPause()

    @run_pending_tasks
    def onSaveInstanceStateA(self):
        self.activityA.onSaveInstanceState(self.savedInstanceState)

    @run_pending_tasks
    def onCreateB(self):
        self.activityB.onCreate(self.savedInstanceState)

    @run_pending_tasks
    def onResumeB(self):
        self.activityB.onResume()
        self._run_timer_tasks()

    @run_pending_tasks
    def notifyTimedOut(self):
        self._run_timer_tasks()

    @run_pending_tasks
    def onPauseB(self):
        self.activityB.onPause()

    def expectInReadyState(self):
        self.assertEqual('READY', self.activityB.delegate_instance.state_machine.getCurrentStateName())

    # %%

    #
    # 以下の行は自動生成されているので直接編集しないでください。
    #
    # Generated by Test Case Generator
    # https://rubygems.org/gems/test_case_generator
    #

    @print_patterns(['onCreateA', 'onResumeA', 'onPauseA', 'onSaveInstanceStateA', 'onCreateB', 'onResumeB', 'notifyTimedOut', 'onPauseB', 'expectInReadyState'])
    def test_onCreateA_onResumeA_onPauseA_onSaveInstanceStateA_onCreateB_onResumeB_notifyTimedOut_onPauseB_expectInReadyState(self):
        self.onCreateA()
        self.onResumeA()
        self.onPauseA()
        self.onSaveInstanceStateA()
        self.onCreateB()
        self.onResumeB()
        self.notifyTimedOut()
        self.onPauseB()
        self.expectInReadyState()

    @print_patterns(['onCreateA', 'onResumeA', 'onPauseA', 'onSaveInstanceStateA', 'onCreateB', 'notifyTimedOut', 'onResumeB', 'onPauseB', 'expectInReadyState'])
    def test_onCreateA_onResumeA_onPauseA_onSaveInstanceStateA_onCreateB_notifyTimedOut_onResumeB_onPauseB_expectInReadyState(self):
        self.onCreateA()
        self.onResumeA()
        self.onPauseA()
        self.onSaveInstanceStateA()
        self.onCreateB()
        self.notifyTimedOut()
        self.onResumeB()
        self.onPauseB()
        self.expectInReadyState()

    @print_patterns(['onCreateA', 'onResumeA', 'onPauseA', 'onSaveInstanceStateA', 'notifyTimedOut', 'onCreateB', 'onResumeB', 'onPauseB', 'expectInReadyState'])
    def test_onCreateA_onResumeA_onPauseA_onSaveInstanceStateA_notifyTimedOut_onCreateB_onResumeB_onPauseB_expectInReadyState(self):
        self.onCreateA()
        self.onResumeA()
        self.onPauseA()
        self.onSaveInstanceStateA()
        self.notifyTimedOut()
        self.onCreateB()
        self.onResumeB()
        self.onPauseB()
        self.expectInReadyState()

    @print_patterns(['onCreateA', 'onResumeA', 'onPauseA', 'notifyTimedOut', 'onSaveInstanceStateA', 'onCreateB', 'onResumeB', 'onPauseB', 'expectInReadyState'])
    def test_onCreateA_onResumeA_onPauseA_notifyTimedOut_onSaveInstanceStateA_onCreateB_onResumeB_onPauseB_expectInReadyState(self):
        self.onCreateA()
        self.onResumeA()
        self.onPauseA()
        self.notifyTimedOut()
        self.onSaveInstanceStateA()
        self.onCreateB()
        self.onResumeB()
        self.onPauseB()
        self.expectInReadyState()

    @print_patterns(['onCreateA', 'onResumeA', 'notifyTimedOut', 'onPauseA', 'onSaveInstanceStateA', 'onCreateB', 'onResumeB', 'onPauseB', 'expectInReadyState'])
    def test_onCreateA_onResumeA_notifyTimedOut_onPauseA_onSaveInstanceStateA_onCreateB_onResumeB_onPauseB_expectInReadyState(self):
        self.onCreateA()
        self.onResumeA()
        self.notifyTimedOut()
        self.onPauseA()
        self.onSaveInstanceStateA()
        self.onCreateB()
        self.onResumeB()
        self.onPauseB()
        self.expectInReadyState()

    @print_patterns(['onCreateA', 'notifyTimedOut', 'onResumeA', 'onPauseA', 'onSaveInstanceStateA', 'onCreateB', 'onResumeB', 'onPauseB', 'expectInReadyState'])
    def test_onCreateA_notifyTimedOut_onResumeA_onPauseA_onSaveInstanceStateA_onCreateB_onResumeB_onPauseB_expectInReadyState(self):
        self.onCreateA()
        self.notifyTimedOut()
        self.onResumeA()
        self.onPauseA()
        self.onSaveInstanceStateA()
        self.onCreateB()
        self.onResumeB()
        self.onPauseB()
        self.expectInReadyState()

    @classmethod
    def checkSanity(cls):
        sane = True
        msg = []
        for method in ['onCreateA', 'onResumeA', 'onPauseA', 'onSaveInstanceStateA', 'onCreateB', 'onResumeB', 'notifyTimedOut', 'onPauseB', 'expectInReadyState']:
            if not hasattr(cls, method):
                msg += [
                    '    def %s(self):' % method,
                    '        pass',
                    '',
                ]
                sane = False

        if not sane:
            print cls.__name__ + ' must implement following method(s):'
            print
            print "\n".join(msg)
            raise SystemExit(1)


if __name__ == '__main__':
    TestNoNetworkSplashScreenController.checkSanity()
    unittest.main()
