# -*- coding: utf-8 -*-
import os
import sys


class DialogController(object):

    def __init__(self, activity, pending_tasks, timer_tasks):
        super(DialogController, self).__init__()
        self.activity = activity
        self.pending_tasks = pending_tasks
        self.timer_tasks = timer_tasks
        self.state_machine = None
        self.constructStateMachine()

    def show_dialog(self):
        self.activity.show_dialog('dialog_tag')

    def dismiss_dialog(self):
        dlg = self.activity.find_fragment_by_tag('dialog_tag')
        if dlg is not None:
            dlg.dismiss()

    def onCreate(self, saved_instance_state):
        self.prepareStateMachine(True, saved_instance_state)
        self.state_machine.onCreate(saved_instance_state)

    def onStart(self):
        pass

    def onResume(self):
        self.state_machine.onResume()

    def onPause(self):
        self.state_machine.onPause()

    def isResumed(self):
        return self.activity.isResumed()

    def onSaveInstanceState(self, out_instance_state):
        self.saveStateMachine(out_instance_state)

    def onStop(self):
        pass

    def onDestroy(self):
        pass

    # TODO: Add or customize action handlers here.

    def post(self, action):
        self.pending_tasks.append(action)
        return action

    def postDelayed(self, action, delayMillis):
        self.timer_tasks.append(action)
        return action

    def removeCallbacks(self, task_id):
        self.pending_tasks[:] = [action for action in self.pending_tasks if action != task_id]
        self.timer_tasks[:] = [action for action in self.timer_tasks if action != task_id]

    def constructStateMachine(self):
        self.state_machine = SplashScreenControllerStateMachine(self)

    # %%

    #
    # 以下の行は自動生成されているので直接編集しないでください。
    #
    # Generated by View Generator
    #

    def prepareStateMachine(self, debug_flag, saved_instance_state):
        self.state_machine.setDebugFlag(debug_flag)
        if (saved_instance_state is not None) and ('state_machine' in saved_instance_state):
            self.state_machine.restoreInstanceState(saved_instance_state['state_machine'])
        else:
            self.state_machine.enterStartState()

    def saveStateMachine(self, out_instance_state):
        out_instance_state['state_machine'] = {}
        self.state_machine.saveInstanceState(out_instance_state['state_machine'])

    # Public method for SplashScreenControllerStateMachine

    def closeDialog(self):
        self.state_machine.closeDialog()

    def cancelDialog(self):
        self.state_machine.cancelDialog()


class SplashScreenControllerStateMachine(object):

    class_instance_counter = 0

    ENTRY_POINT = 0
    DIALOG = 1
    CLOSED = 2

    def __init__(self, parent_context):
        super(SplashScreenControllerStateMachine, self).__init__()
        self.instance_index = SplashScreenControllerStateMachine.class_instance_counter
        SplashScreenControllerStateMachine.class_instance_counter += 1
        self.parent_context = parent_context
        self.mDebugFlag = False
        self.mInTransition = False
        self.mCurrentState = 0
        self.mGroupState = []
        self.mPendingState = 0
        self.mPendingEvent = None
        self.mPendingPriority = 0
        self.mDebugLevel = 2

    def getCurrentState(self):
        return self.mCurrentState

    def getCurrentStateName(self):
        return SplashScreenControllerStateMachine.STATE_TABLE[self.mCurrentState]

    def setCurrentState(self, state):
        self.mCurrentState = state
        self.clearPendingState()
        self.debugPrintCurrentState('ENTER STATE')

    def debugPrintCurrentState(self, msg):
        state = self.mCurrentState
        if self.mDebugFlag and state < len(SplashScreenControllerStateMachine.STATE_TABLE):
            print "SplashScreenControllerStateMachine(%d): %s: %s" % (self.instance_index, msg, SplashScreenControllerStateMachine.STATE_TABLE[state])

    def clearPendingState(self):
        self.mPendingAction = None
        self.mPendingPriority = 0
        self.mPendingState = 0

    def isInTransition(self):
        return self.mInTransition

    def isDebugFlag(self):
        return self.mDebugFlag

    def setDebugFlag(self, debugFlag):
        self.mDebugFlag = debugFlag

    def getDebugLevel(self):
        return self.mDebugLevel

    def setDebugLevel(self, debugLevel):
        self.mDebugLevel = debugLevel

    def enterStartState(self):
        self.debugPrintCurrentState('START STATE')
        self.clearPendingState()

    def evaluatePendingCondition(self):
        if self.mPendingEvent is None or self.mPendingState == 0:
            return

    def saveInstanceState(self, out_instance_state):
        while True:
            break

        out_instance_state['mCurrentState'] = self.mCurrentState
        self.debugPrintCurrentState('SAVE STATE')

    def restoreInstanceState(self, saved_instance_state):
        self.mCurrentState = saved_instance_state['mCurrentState']
        self.debugPrintCurrentState('RESTORE STATE')

        while True:
            break

    def onCreate(self, saved_instance_state):
        if self.mInTransition:
            raise RuntimeError("inTransition must be false. HINT: Use postOnCreate.")

        self.evaluatePendingCondition()

        self.mInTransition = True

        if self.getDebugLevel() >= 2:
            print '  onCreate'

        while True:
            if self.mCurrentState == SplashScreenControllerStateMachine.ENTRY_POINT:
                self.setCurrentState(SplashScreenControllerStateMachine.DIALOG)
                self.parent_context.show_dialog()
                break

            # default
            break

        self.mInTransition = False

    def onResume(self):
        if self.mInTransition:
            raise RuntimeError("inTransition must be false. HINT: Use postOnResume.")

        self.evaluatePendingCondition()

        self.mInTransition = True

        if self.getDebugLevel() >= 2:
            print '  onResume'

        while True:
            # default
            break

        self.mInTransition = False

    def onPause(self):
        if self.mInTransition:
            raise RuntimeError("inTransition must be false. HINT: Use postOnPause.")

        self.evaluatePendingCondition()

        self.mInTransition = True

        if self.getDebugLevel() >= 2:
            print '  onPause'

        while True:
            # default
            break

        self.mInTransition = False

    def closeDialog(self):
        if self.mInTransition:
            raise RuntimeError("inTransition must be false. HINT: Use postCloseDialog.")

        self.evaluatePendingCondition()

        self.mInTransition = True

        if self.getDebugLevel() >= 2:
            print '  closeDialog'

        while True:
            if self.mCurrentState == SplashScreenControllerStateMachine.DIALOG:
                self.parent_context.dismiss_dialog()
                self.setCurrentState(SplashScreenControllerStateMachine.CLOSED)
                break

            # default
            break

        self.mInTransition = False

    def cancelDialog(self):
        if self.mInTransition:
            raise RuntimeError("inTransition must be false. HINT: Use postCancelDialog.")

        self.evaluatePendingCondition()

        self.mInTransition = True

        if self.getDebugLevel() >= 2:
            print '  cancelDialog'

        while True:
            if self.mCurrentState == SplashScreenControllerStateMachine.DIALOG:
                self.parent_context.dismiss_dialog()
                self.setCurrentState(SplashScreenControllerStateMachine.CLOSED)
                break

            # default
            break

        self.mInTransition = False

    STATE_TABLE = ["ENTRY_POINT", "DIALOG", "CLOSED"]
